# doc.toml – Document settings

[document]
type       = "Bachelor-Thesis" # Freitext
title      = "Generative KI zur Code-Generierung in ServiceNow-Implementierungen: Eine experimentelle Studie zu Entwicklungseffizienz und Codequalität"
subtitle   = "" # optional
program    = "Wirtschaftsinformatik - Business Information Systems"
date       = "08.10.2026"
degree     = "Bachelor of Science (B.Sc.)" #"Bachelor of Science (B.Sc.)" #optional – leer lassen für Hausarbeit/Projektarbeit
module     = "Informationsmanagement"      #optional – wird angezeigt wenn degree leer ist
supervisor = "Dipl.-Kfm. Henning Mertes" #optional

[university]
name     = "FOM Hochschule für Oekonomie & Management"
location = "Düsseldorf"

[[authors]]
name = "Eric Janz"
id   = "713684"

[options]
confidential        = false   # true  → include confidentiality notice
print_mode          = false   # true  → duplex printing
declaration         = true   # false → omit declaration of independent work
ai_register         = true    # false → omit AI tools register
appendix            = false   # true  → include appendix (chapters/appendix.typ)
split_bibliography  = false  # true  → group Quellenverzeichnis by source type (books → articles → online)
                              #         uses refs.bib; entries sorted by type then author via fom-split.csl
